# -*- encoding : utf-8 -*-
production:
  omniauth:
    vkontakte:
      key: 4147410
      secret: ma0pKZKffmaBK8TmJIHn
      scope: notify,friends, photos, offline, video
    instagram:
      key: 778d4cf1dc9448268c0adef8d5048dc0
      secret: 8fd63527bebe4cbd9c3f348e9e4d9d84
    twitter:
      key: UTA6rdnRs5OJL8htZd8QPw
      secret: mAvoZ0j7dpDEEpDFwuJwrGz7R7QdQCt7eoUxOcyrDI

  analytics:
    yandex: 25270682
    google: UA-51939572-1
  siteheart: 710265

development:
  omniauth:
    vkontakte:
      key: 4251718
      secret: 1niLBXNpjxzY6qKlyfdA
      scope: notify,friends, photos, offline, video
    instagram:
      key: e47e454da7044bfeab18202eed041677
      secret: f844054e6c1c47ec86ef4aafc5157ff1
  analytics:
    yandex: 25270682
    google: UA-51939572-1
  siteheart: 710260
